### ISSUE TITLE
Cannot GET /register/new

### ISSUE THREAD

**Issue by tpglitch** [UiharuKazari2008/SimpleCabRFID#1]
I installed this but when I create a new one I get this error.

**Comment by UiharuKazari2008** [comment]
Was this done via the web interface or were you manually trying to call the API?

**Comment by tpglitch** [comment]
The web interface- right after I followed the instructions with configuring config.json and stuff

**Comment by tpglitch** [comment]
I also cannot GET /register/scan

**Comment by tpglitch** [comment]
![image](https://github.com/UiharuKazari2008/openCreditIC/assets/123958345/1a397fb8-62a9-4c46-9cc6-43e8a5097c9f)
Hopefully this can get fixed- it is the only free and open source solution I could find.

**Comment by tpglitch** [comment]
Also if i provide a customer id i get this:
![image](https://github.com/UiharuKazari2008/openCreditIC/assets/123958345/435839b3-7b40-4a65-9c89-4c7208cac9ab)

**Comment by tpglitch** [comment]
![image](https://github.com/UiharuKazari2008/openCreditIC/assets/123958345/541cca2c-6b9b-456b-9b60-b5525ca93d6c)

**Comment by UiharuKazari2008** [comment]
Fixed, please use `git pull` and try again. Most of the testing was done with scanning cards using the POS reader not with manual data entry so understandable that some of that stuff may need more testing

**Comment by tpglitch** [comment]
Works now, thanks!

**Comment by tpglitch** [comment]
Also, I have one more question- how do I do the scanning thing and setup a similar POS to what u did?

**Comment by tpglitch** [comment]
New similar issue found- scan feature in deposit or creation
![image](https://github.com/UiharuKazari2008/openCreditIC/assets/123958345/d05b4010-ecfa-4867-8244-6374959528d7)

**Comment by UiharuKazari2008** [comment]
In configuration:
https://github.com/UiharuKazari2008/openCreditIC?tab=readme-ov-file#configuration

You would flash a reader with https://github.com/UiharuKazari2008/openCreditIC/blob/main/CardReader-POS/CardReader-POS.ino and register it using

/create/pos/`WIFI Mac Address`?name=`Name of Reader`&location=`Location like FrontDesk`
